CREATE TABLE Usuario
(
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
  nome NVARCHAR(100) NOT NULL,
  email NVARCHAR(255) UNIQUE NOT NULL,
  senha NVARCHAR(255) NOT NULL,
  ativo BIT NOT NULL DEFAULT 1,
  admin BIT NOT NULL DEFAULT 0,
  criado_em DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
  atualizado_em DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

CREATE TABLE Perfil
(
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
  bi NVARCHAR(50) UNIQUE,
  genero CHAR(1) CHECK (genero IN ('M', 'F')),
  data_nascimento DATE,
  foto NVARCHAR(MAX) DEFAULT 'fotopadrao.webp',
  bio NVARCHAR(MAX),
  usuario_id UNIQUEIDENTIFIER UNIQUE NOT NULL,
  criado_em DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
  atualizado_em DATETIME2 NOT NULL DEFAULT SYSDATETIME(),


  CONSTRAINT fk_usuario FOREIGN KEY (usuario_id) references Usuario(id) ON DELETE CASCADE
);

CREATE TABLE Area
(
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
  titulo NVARCHAR(100) NOT NULL,
  descricao NVARCHAR(255)
);

CREATE TABLE TipoPergunta
(
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
  titulo NVARCHAR(100) NOT NULL,
  codigo VARCHAR(10) NOT NULL,
  descricao NVARCHAR(255)
);

CREATE TABLE Quiz
(
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
  titulo NVARCHAR(100) NOT NULL,
  descricao NVARCHAR(255),
  tempo INT DEFAULT 0 CHECK (tempo >= 0),
  -- tempo em segundos (s)
  privado BIT DEFAULT 0,
  area_id UNIQUEIDENTIFIER NOT NULL,
  autor_id UNIQUEIDENTIFIER NOT NULL,
  criado_em DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
  atualizado_em DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

  CONSTRAINT fk_autor FOREIGN KEY (autor_id) references Usuario(id),
  CONSTRAINT fk_area FOREIGN KEY (area_id) references Area(id)
);

CREATE TABLE Pergunta
(
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
  pergunta NVARCHAR(200) NOT NULL,
  tipo_pergunta_id UNIQUEIDENTIFIER NOT NULL,
  quiz_id UNIQUEIDENTIFIER NOT NULL,
  dificuldade TINYINT DEFAULT 1 CHECK (dificuldade BETWEEN 1 AND 3),
  criado_em DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

  CONSTRAINT fk_tipo_pergunta FOREIGN KEY (tipo_pergunta_id) references TipoPergunta(id),
  CONSTRAINT fk_quiz_pergunta FOREIGN KEY (quiz_id) references Quiz(id) ON DELETE CASCADE
);

CREATE TABLE Resposta
(
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
  resposta NVARCHAR(255) NOT NULL,
  pergunta_id UNIQUEIDENTIFIER NOT NULL,
  correto BIT DEFAULT 0,
  criado_em DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

  CONSTRAINT fk_pergunta FOREIGN KEY (pergunta_id) references Pergunta(id) ON DELETE CASCADE
);

CREATE TABLE Pontuacao
(
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
  usuario_id UNIQUEIDENTIFIER NOT NULL,
  quiz_id UNIQUEIDENTIFIER NOT NULL,
  pontos INT NOT NULL,
  tempo INT CHECK (tempo >= 0),
  criado_em DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
  atualizado_em DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

  CONSTRAINT fk_usuario_pontuacao FOREIGN KEY (usuario_id) REFERENCES Usuario(id),
  CONSTRAINT fk_quiz_pontuacao FOREIGN KEY (quiz_id) REFERENCES Quiz(id)
);

CREATE TABLE RespostaUsuario
(
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
  usuario_id UNIQUEIDENTIFIER NOT NULL,
  pergunta_id UNIQUEIDENTIFIER NOT NULL,
  resposta_id UNIQUEIDENTIFIER NOT NULL,
  criado_em DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

  CONSTRAINT fk_usuario_resposta FOREIGN KEY (usuario_id) REFERENCES Usuario(id),
  CONSTRAINT fk_pergunta_resposta FOREIGN KEY (pergunta_id) REFERENCES Pergunta(id) ON DELETE CASCADE,
  CONSTRAINT fk_resposta FOREIGN KEY (resposta_id) REFERENCES Resposta(id),
  CONSTRAINT uq_usuario_pergunta UNIQUE (usuario_id, pergunta_id)
);

CREATE TABLE PermissaoQuizPrivado
(
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
  usuario_id UNIQUEIDENTIFIER NOT NULL,
  quiz_id UNIQUEIDENTIFIER NOT NULL,
  permitido BIT NOT NULL DEFAULT 0,
  criado_em DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

  CONSTRAINT fk_permissao_usuario FOREIGN KEY (usuario_id) REFERENCES Usuario(id),
  CONSTRAINT fk_quiz_permissao FOREIGN KEY (quiz_id) REFERENCES Quiz(id) ON DELETE CASCADE,
);

